name: Build Rust for ARM (OCI)

on:
  push:
    branches:
      - main # Se ejecuta cuando subes cambios a main

jobs:
  build-arm:
    runs-on: ubuntu-latest # Corre en una máquina x86_64
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Instalar compilador cruzado
        run: sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu

      - name: Compilar para ARM64
        run: cargo build --target=aarch64-unknown-linux-gnu --release

      - name: Subir binario como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: binario-arm
          path: target/aarch64-unknown-linux-gnu/release/tu_programa
